### ISSUE TITLE
What does the .exe file in releases do?

### ISSUE THREAD

**Issue by fjeddy** [egomeh/anno1800-scripting-api#12]
You have a .exe file in releases, the first and only one, and there is some talk about making it more user-friendly.

What exactly does, or well, is the .exe file supposed to do? From the description of the release, it can seem like a helper program to the script, and not the script itself?

I tried running it, seems to hook up to the game, but nothing happens. Does the script support moving resources between worlds btw?

**Comment by egomeh** [comment]
That was the first program that I made as a standalone. It just used the API to make sure that all goods on all player owned islands are between 25 and (max - 50) or something like that.

Yeah, the API is a little outdated for the time. I apologize. I've not had the time yet to update it. I'll get it updated as soon as I get a chance!
