### ISSUE TITLE
Impossible to use for someone not versed in the code

### ISSUE THREAD

**Issue by CamilleHbp** [egomeh/anno1800-scripting-api#13]
Hello!

I would like to understand how to use and contribute to this program, but it's impossible for me to understand how to build and use this. I've built something called `GoodMinMax` and Monocle but they all crash the game.

Would you be willing to setup a call, maybe on [Jitsi](https://meet.jit.si/), if you don't have the time to write all this? Otherwise just some quick info here on Github would already be nice.

 I could afterwards take a few screenshots, write down my process, and make some kind of tutorial for those interested.

As of now, I think the project is unusable to anyone but you and the other contributors. It's a shame because it looks like a very nice project in which a lot of effort has been put. It's sad that it is missing only a little bit of doc to get the community to help you and try it on their own.

**Comment by egomeh** [comment]
Hi,

Thank you so much for your interest. You're absolutle right about the project needing a loving touch especially in the user facing direction.

I'm more than happy to have a chat with you. I could (and should) write more stuff on github as well, but even keeping the project somewhat working is already a lot of labour. I hope to get around to it eventually but my first priority is to try to keep up with functionality.

Again, I'd be happy to have a chat aobut it :) How do I reach you?

**Comment by CamilleHbp** [comment]
I've had a really nice overview of the project. It is not working at the moment but I'll try to create a guide to get the project up and running.

I'll fork the repo, do my things and make a PR here. Thank you @egomeh!

**Comment by shellwhale** [comment]
Had the same feeling about a year and a half ago, I'm coming back today to see if I might achieve something this time :)

**Comment by shellwhale** [comment]
I myself cannot make Monocle or GoodMinMax work

```csharp
using System.Threading;

GoodsMinMax.Run();

class GoodsMinMax
{
    private static bool keepRunning = true;

    public static void Run()
    {
        Console.CancelKeyPress += delegate (object sender, ConsoleCancelEventArgs e) {
            e.Cancel = true;
            GoodsMinMax.keepRunning = false;
        };

        Console.WriteLine("Drawing wand...");
        Console.WriteLine("Yelling \"Resourcius minimalus maximus\"");
        Telegraph telegraph = new Telegraph();
        Console.WriteLine("Hoping things are working :S");

        while (keepRunning)
        {
            List<uint> areas;
            telegraph.GetAllAreas(out areas);

            foreach (uint area in areas)
            {
                List<IslandInfo> islands;
                telegraph.GetWorldIslands(area, true, out islands);

                foreach (IslandInfo island in islands)
                {
                    Console.WriteLine(island.name);
                }
            }

            Thread.Sleep(1000);
        }
    }
}
```

I tried this but I'm getting a crash. @CamilleHbp I'm down for a call as well if you can pass me some info as well.

**Comment by CamilleHbp** [comment]
Well, I'm not sure that I can pass some really useful info to fix the mod at the moment, but I have recorded the call. I just need to sit down and document it all in written format. It is mostly information about the injection process, and how the program communicates with Anno 1800's process. I would gladly have a call with you, but it might in the week-end since I'd like to review all that info @shellwhale :)

**Comment by shellwhale** [comment]
@CamilleHbp sounds good, how do I reach you?

**Comment by CamilleHbp** [comment]
Hey @shellwhale , sorry! I've invited you to a private repository with a way to contact me there. :)

**Comment by jjalexander** [comment]
@CamilleHbp I am also interested in getting this project to work. Any chances I could also see/hear the recording?

**Comment by CamilleHbp** [comment]
> @CamilleHbp I am also interested in getting this project to work. Any chances I could also see/hear the recording?

I'd need to find it. I'll try to do so before I leave at the end of the month, but no promises. :S
