### ISSUE TITLE
Cannot get monocle to run

### ISSUE THREAD

**Issue by tkchouaki** [egomeh/anno1800-scripting-api#3]
Hello,
I am very interested by this API & I would like to use it.
I followed the steps described in the readme but I'm having trouble to make it work.
More specifically:
- Launch the solution (still in debug mode) : The only runnable project in this solution is SurvellianceVan so I set it as the project to run. I looked at the code & it appeared to me that it creates a server and waits for clients
- Run code using the monocle project : When I run monocle, I get a bug at the line with the m_Socket.Connect in the Telegraph constructor. I tried changing the port to match the one indicated in SurvellianceVan without any success.

Can you please give more details on how to use it ?
Best regards.

**Comment by egomeh** [comment]
Hi,

thank you for your interest in the project.

The API does not work at the moment. Every time there is an update, the API breaks. I have not yet had a chance to update it. If you want, I can update you on when it's up to date.

It'll likely break again once we reach the next DLC update though.

Thank you

**Comment by tkchouaki** [comment]
Hello,
Thank you for your reply. 
I would really like to be informed when the API works.
Regards.

**Comment by egomeh** [comment]
Hi,

Today I've managed to get back _some_ functionality. There are still some things missing, but hopefully it should not take too long now :)

Do you play the game through steam or uplay?

**Comment by tkchouaki** [comment]
Hello,
I have it installed through uplay.

**Comment by egomeh** [comment]
Alright. There is some issue with the uplay version, namely that it is a different binary than the one you get through steam.

It's not hugely different, but the code needs to be tweaked to fit the uplay version.

In order to fix that, I need someone with the uplay version to help me out as I have the steam version.

**Comment by tkchouaki** [comment]
I'll be glad to help
