### ISSUE TITLE
API Insights

### ISSUE THREAD

**Issue by NiHoel** [egomeh/anno1800-scripting-api#4]
How did you obtain all the function offsets in TomCruise/dllmain.cpp : ComputeFunctionOffsets?
Would it be possible to extract more game statistics (e.g. number of factories on island, ship unload statistics - as displayed in the storage tab)?

**Comment by egomeh** [comment]
Hi,

Thank you for your interest!

> How did you obtain all the function offsets in TomCruise/dllmain.cpp : ComputeFunctionOffsets?

I'm not using a particular method. I try to collect information wherever I can and string it together. 

> Would it be possible to extract more game statistics (e.g. number of factories on island, ship unload statistics - as displayed in the storage tab)?

Most likely. It's quite hit-and-miss what is easy and what is not in this context. We'd have to try out the particular thing you're looking for. Some things might seem hard, but is in reality easy and vice versa.

Send me a private message if you want more info.

Cheers
